// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package repository

import (
	"context"
)

type Querier interface {
	CreateTransaction(ctx context.Context, db DBTX, arg CreateTransactionParams) (Transaction, error)
	CreateUserBalance(ctx context.Context, db DBTX, arg CreateUserBalanceParams) (UserBalance, error)
	UpdateUserBalance(ctx context.Context, db DBTX, arg UpdateUserBalanceParams) error
}

var _ Querier = (*Queries)(nil)
