// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: transaction.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (
    user_id,
    kind,
    amount,
    created_at
) VALUES (
  $1, $2, $3, now()
) RETURNING id, user_id, kind, amount, created_at
`

type CreateTransactionParams struct {
	UserID int64
	Kind   Kind
	Amount pgtype.Numeric
}

func (q *Queries) CreateTransaction(ctx context.Context, db DBTX, arg CreateTransactionParams) (Transaction, error) {
	row := db.QueryRow(ctx, createTransaction, arg.UserID, arg.Kind, arg.Amount)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.Amount,
		&i.CreatedAt,
	)
	return i, err
}
