with-expecter: true
dir: "."
outpkg: mocks

packages:
  github.com/majidmohsenifar/heli-tech/transaction-service/repository:
    interfaces:
      Querier:
        config:
          filename: querier.go
  github.com/majidmohsenifar/heli-tech/transaction-service/service/transaction:
    interfaces:
      TransactionEventManager:
        config:
          filename: transaction_event_manager.go
