with-expecter: true
dir: "."
outpkg: mocks

packages:
  github.com/majidmohsenifar/heli-tech/transaction-service/repository:
    interfaces:
      Querier:
        config:
          filename: querier.go
