// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Role struct {
	ID   int32
	Code string
}

type RolesRoute struct {
	RoleID  int32
	RouteID int32
}

type Route struct {
	ID          int32
	Path        string
	Description pgtype.Text
}

type User struct {
	ID       int64
	Email    string
	Password string
}

type UsersRole struct {
	UserID int32
	RoleID int32
}
