// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package repository

import (
	"context"
)

type Querier interface {
	AddRoleToUser(ctx context.Context, db DBTX, arg AddRoleToUserParams) error
	CreateUser(ctx context.Context, db DBTX, arg CreateUserParams) (User, error)
	GetRoleByCode(ctx context.Context, db DBTX, code string) (Role, error)
	GetRouteByPath(ctx context.Context, db DBTX, path string) (Route, error)
	GetUserByEmail(ctx context.Context, db DBTX, email string) (User, error)
}

var _ Querier = (*Queries)(nil)
