// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: role_route.sql

package repository

import (
	"context"
)

const getRouteByPath = `-- name: GetRouteByPath :one
SELECT id, path, description FROM routes
WHERE path = $1 LIMIT 1
`

func (q *Queries) GetRouteByPath(ctx context.Context, db DBTX, path string) (Route, error) {
	row := db.QueryRow(ctx, getRouteByPath, path)
	var i Route
	err := row.Scan(&i.ID, &i.Path, &i.Description)
	return i, err
}
